services:
  mongo1:
    image: mongo:7
    container_name: clinica_mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - clinica-net
    command: ["--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  node1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clinica_node1
    environment:
      PORT: 3000
      NODE_NAME: node1
      MONGO_HOSTS: clinica_mongo1:27017
      MONGO_DB: clinica_dental
    ports:
      - "3001:3000"
    networks:
      - clinica-net
    depends_on:
      mongo1:
        condition: service_healthy

  node2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clinica_node2
    environment:
      PORT: 3000
      NODE_NAME: node2
      MONGO_HOSTS: clinica_mongo1:27017
      MONGO_DB: clinica_dental
    ports:
      - "3002:3000"
    networks:
      - clinica-net
    depends_on:
      mongo1:
        condition: service_healthy

  node3:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clinica_node3
    environment:
      PORT: 3000
      NODE_NAME: node3
      MONGO_HOSTS: clinica_mongo1:27017
      MONGO_DB: clinica_dental
    ports:
      - "3003:3000"
    networks:
      - clinica-net
    depends_on:
      mongo1:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: clinica_nginx
    ports:
      - "8080:80"
    networks:
      - clinica-net
    depends_on:
      - node1
      - node2
      - node3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clinica_frontend
    ports:
      - "5173:5173"
    networks:
      - clinica-net
    depends_on:
      - nginx

networks:
  clinica-net:
    driver: bridge

volumes:
  mongo1_data: